project_name: tfu
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
brews:
  - tap:
      owner: dirien
      name: homebrew-dirien

    commit_author:
      name: dirien
      email: engin.diri@mail.schwarz

    folder: Formula

    homepage: "https://github.com/dirien/tfu"
    description: "tfu is a Terraform helper to update the providers."
    license: "Apache License 2.0"

archives:
  - format_overrides:
      - goos: windows
        format: zip
